### ISSUE TITLE
Add live-reload example

### ISSUE THREAD

**Issue by mikker** [pandeiro/agua#3]
This is really good but I've been struggling to integrate this into something like [tenzing](https://github.com/martinklepsch/tenzing) (or the other way around).

**Comment by mikker** [comment]
Alternatively you could make the jetty optional and provide agua's `serve` as a regular Ring-handler. That might make this more _includable_ into other stuff. If that's even possible.

**Comment by pandeiro** [comment]
Hi @mikker, so... this would be really cool, I agree. I think that the easiest way to integrate any of the ideas here into a bigger, properly laid out project, though, may just be copying (or calling, when possible) the functions that you want, like `prerender`. The whole thing is kind of a bundle of yarn though, because the point was not really a composable unit but a pattern for quick, one-off standalone apps.

As for live reloading behavior, I don't see how it's possible given that these macros would be used in a single file, outside of a project structure -- hence without the proper source-paths and resource-paths defined and available for watching. Do you see a way?

For less one-off stuff, as a foundation for a larger project for instance, I think you're definitely in better hands starting from something like tenzing or the figwheel template.

**Comment by mikker** [comment]
I see what your saying. This was also the way that I got the furthest – picking from `prerender`. I will of course share if I get anywhere with this. Probably not. Thanks anyway :new_moon_with_face:
